name: text_to_speech
description: "Une application Flutter pour convertir du texte en MP3."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  audioplayers: ^6.4.0
  provider: ^6.1.5
  http: ^1.4.0  # ← REMETTRE LA VERSION RÉCENTE
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  audio_video_progress_bar: ^2.0.0
  rxdart: ^0.28.0
  another_flushbar: ^1.12.29
  url_launcher: ^6.3.0
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  window_manager: ^0.5.0
  collection: ^1.18.0
  shared_preferences: ^2.2.5
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  file_picker: ^10.1.9
  matcher: ^0.12.16+1
  yaml: ^3.1.2
  app_settings: ^6.1.1
  flutter_tts: ^4.2.2
  cloud_text_to_speech: ^2.3.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.3.3

# 🔧 FORCER LA VERSION HTTP POUR TOUS LES PACKAGES
dependency_overrides:
  http: ^1.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/images/